name: Github Actions Trading
on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  check_program_exit_status:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: python3 ./src/main.py < .github/workflows/quit-file.txt
      timeout-minutes: 1
  run_tests:
    needs:
      - check_program_exit_status
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
      options: --privileged
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: |
        ./tests/script_tester.sh
      timeout-minutes: 1
  push_to_mirror:
    needs:
      - run_tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: git@github.com:EpitechPromo2027/B-CNA-410-NAN-4-1-trade-adam.lesage.git
        ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
